### ISSUE TITLE
[Design] Orçamento de Serviços de Design para a Python Norte 2025

### ISSUE THREAD

**Issue by jailsonpj** [PythonNorteBrasil/pynorte2025-org#1]
Pedir orçamento de Design para as Desgins. 

contato: Adria Afonso e Yasmin Barreto.

**Comment by jailsonpj** [comment]
[Uploading Orçamento de Serviços.pdf…]()

**Comment by thaty-maru** [comment]
50% do valor já foi solicitado para pagamento à APYB.

**Comment by thaty-maru** [comment]
50% do valor já foi solicitado para pagamento à APYB.

**Comment by jailsonpj** [comment]
Acredito que o pagamento do 50% já foi feito a Yasmin e Raquel. Vou fechar essa Issue. Depois a gente abri outra pra pagar os outros 50%.
