### ISSUE TITLE
Padronização do nome do eventos e uso das redes sociais.

### ISSUE THREAD

**Issue by gabrovskii** [PythonNorteBrasil/pynorte2025-org#5]
# Padronização do nome do eventos e uso das redes sociais.

A Python Norte cresceu e está se tornando um evento mais complexo. Por conta disso, surgiu a necessidade de definir alguns padrões, visando à organização das próximas edições. Tópicos a serem discutidos:

1. Padronização das nomenclaturas: Python Norte, PyNorte, Python Amazônia, etc.
2. Acesso às redes sociais.
3. Grupo do Telegram para divulgação dos eventos regionais anuais.

O propósito é facilitar o acesso da população aos conteúdos da Python Norte e criar, de forma organizada, a distinção entre os eventos da **Python Norte** e os conteúdos da **PyNorte.**

# SUGESTÂO TEXTO

Olá, bom dia! Tudo bem?

A organização dos eventos Python Norte 2023, 2024 e 2025, juntamente com os organizadores do PyLadies Manaus e do PyData Manaus, discutiu e decidiu que seria melhor desvincular o evento e o nome "Python Norte" deste grupo no Telegram da PyNorte. O intuito é focar exclusivamente nos aspectos relacionados ao evento anual e reunir as comunidades que participam diretamente dele, assim como de outras redes sociais, incluindo o GitHub.  

Acreditamos que criar redes sociais específicas para o evento será o melhor caminho. Gostaríamos apenas de sugerir aos administradores do grupo PyNorte que considerassem a ideia de alterar o nome para algo como "Python Amazônia". E de que não estamos dividindo a comunidade mas sim o foco dos grupos :) .

Agradecemos muito pela compreensão.

Atenciosamente,  
Equipe de Organização Python Norte 2025

**Comment by jailsonpj** [comment]
Olá, bom dia! Tudo bem?

A organização dos eventos Python Norte 2023, 2024 e 2025, as organizadores das PyLadies Manaus e do PyData Manaus, discutiram e perceberam que ter acesso total às redes sociais facilitaria na divulgação e comunicação do evento. Nosso objetivo é renomear o @ das redes sociais para "Python Norte", a fim de manter o mesmo padrão de outras conferências regionais, tais como Python Nordeste, Python Sudeste, etc, que possuem suporte da infraestrutura da APyB

Dessa forma, sugerimos aos administradores do grupo PyNorte que considerassem a ideia de alterar o nome para algo como "Python Amazônia". A organização deste ano pretende criar um novo grupo para focar exclusivamente nos aspectos relacionados ao evento anual e reunir as pessoas que participaram dele, chamado Python Norte 2025.

Agradecemos pelo apoio durante esses anos de evento e queremos reiterar que o objetivo não é segregar a comunidade, mas sim organizar e fazer os eventos de maneira positiva para todos.

**Comment by thaty-maru** [comment]
Olá, bom dia! Tudo bem?

A conferência Python Norte tem como objetivo destacar a comunidade Python na região Norte e também ser uma ponte de conhecimento trazendo pessoas de outras regiões para compartilhar seu conhecimento. A organização das edições do evento, em conjunto com os organizadores das PyLadies Manaus e do PyData Manaus, discutiram e perceberam que ter acesso total às redes sociais facilitaria na divulgação e comunicação do evento. Nosso objetivo é renomear o @ das redes sociais para "Python Norte", a fim de manter o mesmo padrão de outras conferências regionais, tais como Python Nordeste, Python Sudeste, etc, que possuem suporte da infraestrutura da APyB. Com isso estaríamos mantendo a identidade visual e objetivos do grupo PyNorte preservados.

Relativo ao nome deste grupo, concordamos com a ideia de alteração para "Python Amazônia". A organização da conferência deste ano pretende criar um novo grupo para focar exclusivamente nos aspectos relacionados ao evento anual e reunir as pessoas que participaram dele, chamado Python Norte 2025, e caso haja interesse convidamos todos a participar.

Agradecemos pelo apoio durante esses anos de evento, além de toda a história de crescimento que trouxeram consigo de comunidade Python na região Norte, e queremos reiterar que o objetivo não é segregar a comunidade, e sim organizar e fazer os eventos de maneira positiva para todos.

Ficamos à disposição e sigamos juntos enaltecendo o Norte.

Atenciosamente,
Equipe Organizadora Python Norte 2025

**Comment by jailsonpj** [comment]
Vou fechar essa Issue. @gabrovskii acho legal vc abrir uma issue para criação das redes sociais da Python Norte .
